version: '3.7'
services:
  gerocuidado-saude-api:
    image: node:18.13.0
    container_name: gerocuidado-saude-api
    volumes:
      - .:/home/node/app
    entrypoint: bash /home/node/app/.docker/entrypoint.sh
    environment:
      - NODE_ENV=development
    ports:
      - '3003:3003'
      - '7003:9003'
    depends_on:
      - gerocuidado-saude-db
    networks:
      - gerocuidado-saude-net

  gerocuidado-saude-db:
    build:
      context: ./.docker/postgres
      dockerfile: Dockerfile
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - './db/postgres:/var/lib/postgresql/data'
      - './.docker/postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf'
    environment:
      - POSTGRES_DB=gerocuidado-saude-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5003:5003'
    networks:
      - gerocuidado-saude-net

networks:
  gerocuidado-saude-net:
    driver: bridge
